[package]
name = "binary_string"
version = "0.1.0"
authors = ["Jeff Smits <jeff.smits@gmail.com>"]

[dependencies]

[[bin]]
name = "binary_string"
path = "src/main.rs"

[[bin]]
name = "implicit_state"
path = "src/implicit_state.rs"

[[bin]]
name = "observing"
path = "src/observing.rs"

