[package]
name = "binary_palindrome"
version = "0.1.0"
authors = ["jeff"]

[dependencies]

[[bin]]
name = "binary_palindrome"
path = "src/main.rs"

[[bin]]
name = "simple"
path = "src/simple.rs"


[[bin]]
name = "grammar_based"
path = "src/grammar_based.rs"

